// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class BB_OA_Mercs {
		units[] = {};
		weapons[] = {};
		requiredVersion = 1.02;
		requiredAddons[] = {"CACharacters", CA_E, "CACharacters_E_Head", "CACharacters2", "CAweapons", "CAweapons2", "CA_Modules_ARTY", "CAWeapons_Kord", "CAWeapons_Warfare_weapons"};
	};
};
