// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class US_Delta_Force_EP1;	// External class reference
		
	class Bandit3_DZ : US_Delta_Force_EP1 {
		displayName = "Reaper";
		accuracy = 1000;	// accuracy needed to recognize type of this target
		faceType = "Man";
		scope = public;
		faction = PMC_BAF;
		canCarryBackPack = 1;
		vehicleClass = "Men";
		camouflage = 0.6;	// how dificult to spot - bigger - better spotable
		model = "bb_oa_mercs\desert_blackop.p3d";
		identityTypes[] = {"Language_BAF","Language_EN_EP1","USMC_Glasses","PMC_Glasses_PMC"};
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"ca\weapons\data\m9_beretta_co"};
		
		class EventHandlers {
			init = "[_this select 0] execvm ""\bb_oa_mercs\scripts\init.sqf""";
		};
		enableGPS = 1;
		
		Items[] = {};
		RespawnItems[] = {};
		linkedItems[] = {};
		respawnLinkedItems[] = {};
		weapons[] = {"Throw","Put","Throw_DZ"};
		respawnWeapons[] = {"Throw","Put","Throw_DZ"};
		respawnMagazines[] = {};
		backpack = "";
		magazines[] = {};
        
		class Wounds {
			tex[] = {};
			mat[] = {"ca\characters_e\us\data\tex1.rvmat", "ca\characters_E\US\data\W1_tex1.rvmat", "ca\characters_E\US\data\W2_tex1.rvmat", "bb_oa_mercs\textures\acr_soldier_nic.rvmat", "bb_oa_mercs\textures\w1_acr_soldier_nic.rvmat", "bb_oa_mercs\textures\w2_acr_soldier_nic.rvmat", "ca\characters_e\heads\male\defaulthead\data\hhl_white.rvmat", "ca\characters_e\Heads\male\DefaultHead\Data\hhl_Wounds.rvmat", "ca\characters_e\Heads\male\DefaultHead\Data\hhl_Wounds2.rvmat"};
		};
	};	
    
	class Survivor4_DZ : US_Delta_Force_EP1 {
		faceType = "Man";
		canCarryBackPack = 1;
		faction = PMC_BAF;
		scope = public;
		vehicleClass = "Men";
		camouflage = 0.6;	// how dificult to spot - bigger - better spotable
		displayName = "Guardian";
		identityTypes[] = {"Language_BAF","Language_EN_EP1","USMC_Glasses","PMC_Glasses_PMC"};
		accuracy = 1000;	// accuracy needed to recognize type of this target
		enableGPS = 1;
		model = "bb_oa_mercs\merc_oa_at.p3d";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\ca\weapons\colt1911\data\colt1911_body_co"};
		
		class EventHandlers {
			init = "[_this select 0] execvm ""\bb_oa_mercs\scripts\init.sqf""";
		};
        
		Items[] = {};
		RespawnItems[] = {};
		linkedItems[] = {};
		respawnLinkedItems[] = {};
		weapons[] = {"Throw","Put","Throw_DZ"};
		respawnWeapons[] = {"Throw","Put","Throw_DZ"};
		respawnMagazines[] = {};
		backpack = "";
		magazines[] = {};
        
		class Wounds {
			tex[] = {};
			mat[] = {"ca\characters_e\civil\harris\data\european-man_01.rvmat", "bb_oa_mercs\textures\W1_european-man_01.rvmat", "bb_oa_mercs\textures\W2_european-man_01.rvmat", "ca\characters_e\civil\harris\data\harris.rvmat", "bb_oa_mercs\textures\W1_european-man_01.rvmat", "bb_oa_mercs\textures\W2_european-man_01.rvmat", "bb_oa_mercs\textures\acr_soldier_nic.rvmat", "bb_oa_mercs\textures\w1_acr_soldier_nic.rvmat", "bb_oa_mercs\textures\w2_acr_soldier_nic.rvmat", "ca\characters_e\heads\male\defaulthead\data\hhl_white.rvmat", "ca\characters_e\Heads\male\DefaultHead\Data\hhl_Wounds.rvmat", "ca\characters_e\Heads\male\DefaultHead\Data\hhl_Wounds2.rvmat"};
		};
	};
};
