// Generated by unRap v1.06 by Kegetys

class CfgModels {
	class Default {
		sectionsInherit = "";
		sections[] = {};
		skeletonName = "";
	};
	
	class Head : Default {
		sections[] = {"osobnost", "brejle"};
		skeletonName = "Head";
	};
	
	class ArmaMan : Default {
		sections[] = {"osobnost", "Head_Injury", "Body_Injury", "l_leg_injury", "l_arm_injury", "r_arm_injury", "r_leg_injury", "clan", "clan_sign", "Camo", "CamoB"};
		skeletonName = "OFP2_ManSkeleton";
	};
	
	class jinpmc : ArmaMan {};
	
	class jinpmcs : ArmaMan {};
	
	class jinpmcss : ArmaMan {};
	
	class jinpmctt : ArmaMan {};
	
	class jinpmcgg : ArmaMan {};
	
	class jinpmcdes : ArmaMan {};
	
	class ArmaWoman : Default {
		sections[] = {"osobnost", "Head_Injury", "Body_Injury", "l_leg_injury", "l_arm_injury", "r_arm_injury", "r_leg_injury", "clan", "clan_sign", "Camo", "CamoB"};
		skeletonName = "WomanSkeleton";
	};
	
	class Vehicle : Default {
		sections[] = {"cislo", "grupa", "side", "sektor", "clan", "clan_sign", "podsvit pristroju", "poskozeni", "L svetlo", "P svetlo", "zasleh"};
	};
	
	class Flag : Default {
		sections[] = {"latka"};
	};
	
	class flag_auto : Flag {};
	
	class flag_alone : Flag {};
};
