// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class jinpmc {
		units[] = {};
		weapons[] = {};
		requiredVersion = 1.0;
		requiredAddons[] = {"CACharacters", CA_E, "CACharacters_E_Head", "CACharacters2"};
	};
};
