// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class GER_Soldier_Scout_EP1;	// External class reference
	class GER_Soldier_MG_EP1;	// External class reference
    
	class Survivor_R : GER_Soldier_MG_EP1 {
		vehicleClass = "Men";
		faction = PMC_BAF;
		displayName = "Veteran";
		camouflage = 0.6;	// how dificult to spot - bigger - better spotable
		model = "\jinpmc\jinpmc.p3d";
		faceType = "Man";
        
		identityTypes[] = {"Language_BAF","Language_EN_EP1","USMC_Glasses","PMC_Glasses_PMC"};
        backpack = "";
		Items[] = {};
		RespawnItems[] = {};
		linkedItems[] = {};
		respawnLinkedItems[] = {};
		weapons[] = {"Throw","Put","Throw_DZ"};
		respawnWeapons[] = {"Throw","Put","Throw_DZ"};
		respawnMagazines[] = {};
		magazines[] = {};
        
		class Wounds {
			tex[] = {"\jinpmc\data\us_soldieracu_co.paa", "\jinpmc\data\us_soldieracu_co_i.paa", "\jinpmc\data\hhl_06_co.paa", "\jinpmc\data\hhl_06_co_i.paa"};
			mat[] = {};
		};
	};
	
	class Survivor_B : GER_Soldier_Scout_EP1 {
		faceType = "Man";
		vehicleClass = "Men";
		faction = PMC_BAF;
		displayName = "Veteran";
		camouflage = 0.6;	// how dificult to spot - bigger - better spotable
		model = "\jinpmc\jinpmcs.p3d";
        
		identityTypes[] = {"Language_BAF","Language_EN_EP1","USMC_Glasses","PMC_Glasses_PMC"};
        backpack = "";
		Items[] = {};
		RespawnItems[] = {};
		linkedItems[] = {};
		respawnLinkedItems[] = {};
		weapons[] = {"Throw","Put","Throw_DZ"};
		respawnWeapons[] = {"Throw","Put","Throw_DZ"};
		respawnMagazines[] = {};
		magazines[] = {};
        
		
		class Wounds {
			tex[] = {"\jinpmc\data\us_soldieracu_cos.paa", "\jinpmc\data\us_soldieracu_cos_i.paa", "\jinpmc\data\hhl_06_co.paa", "\jinpmc\data\hhl_06_co_i.paa"};
			mat[] = {};
		};
	};
};
