// config.bin - 22:42:45 08/04/13, generated in 0.02 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#include "CfgPatches.hpp"
#include "CfgSkeletons.hpp"
#include "CfgModels.hpp"
#include "CfgVehicles.hpp"
