// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class AiA_Vehicles_TransportItems {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"AiA_Vehicles"};
	};
};
