// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class Strategic;	// External class reference
	class Car;	// External class reference
	class Helicopter;	// External class reference
	class LandVehicle;	// External class reference
	class Plane;	// External class reference
	class Ship;	// External class reference
	class Wheeled_APC;	// External class reference
	
	class HMMWV_Base : Car {};
	
	class S1203_TK_CIV_EP1 : Car {};
	
	class LandRover_Base : Car {};
	
	class LandRover_ACR : LandRover_Base {};
	
	class Motorcycle : LandVehicle {
		class TransportItems {
		};
	};
	
	class Bicycle : Motorcycle {
		class TransportItems {};
	};
	
	class Tractor : Car {
		class TransportItems {
		};
	};
	
	class BIS_alice_emptydoor : Car {
		class TransportItems {};
	};
	
	class FoldChair_with_Cargo : Car {
		class TransportItems {};
	};
	
	class Truck : Car {
		class TransportItems {
		};
	};
	
	class V3S_Base : Truck {};
	
	class V3S_Base_EP1 : V3S_Base {};
	
	class T810_Turrets_Base_ACR : Truck {};
	
	class T810_Base_ACR : T810_Turrets_Base_ACR {};
	
	class Ural_Base_withTurret : Truck {};
	
	class Kamaz_Base : Truck {};
	
	class MTVR : Truck {};
	
	class Ural_Base : Ural_Base_withTurret {};
	
	class UralRefuel_Base : Ural_Base {
		class TransportItems {
		};
	};
	
	class KamazRefuel : Kamaz_Base {
		class TransportItems {
		};
	};
	
	class MtvrRefuel : MTVR {
		class TransportItems {
		};
	};
	
	class V3S_Refuel_TK_GUE_EP1 : V3S_Base_EP1 {
		class TransportItems {
		};
	};
	
	class T810Refuel_ACR : T810_Base_ACR {
		class TransportItems {
		};
	};
	
	class UralReammo_Base : Ural_Base {
		class TransportItems {
		};
	};
	
	class KamazReammo : Kamaz_Base {
		class TransportItems {
		};
	};
	
	class MtvrReammo : MTVR {
		class TransportItems {
		};
	};
	
	class V3S_Reammo_TK_GUE_EP1 : V3S_Base_EP1 {
		class TransportItems {
		};
	};
	
	class T810Reammo_ACR : T810_Base_ACR {
		class TransportItems {
		};
	};
	
	class UralRepair_Base : Ural_Base {
		class TransportItems {
		};
	};
	
	class KamazRepair : Kamaz_Base {
		class TransportItems {
		};
	};
	
	class MtvrRepair : MTVR {
		class TransportItems {
		};
	};
	
	class V3S_Repair_TK_GUE_EP1 : V3S_Base_EP1 {
		class TransportItems {
		};
	};
	
	class T810Repair_ACR : T810_Base_ACR {
		class TransportItems {
		};
	};
	
	class BTR40_MG_base_EP1 : Wheeled_APC {
		class TransportItems {
		};
	};
	
	class BRDM2_Base : Wheeled_APC {
		class TransportItems {
		};
	};
	
	class BTR60_TK_EP1 : BRDM2_Base {
		class TransportItems {
		};
	};
	
	class BTR90_Base : Wheeled_APC {
		class TransportItems {
		};
	};
	
	class GAZ_Vodnik_HMG : Wheeled_APC {
		class TransportItems {
		};
	};
	
	class GAZ_Vodnik : GAZ_Vodnik_HMG {};
	
	class LAV25_Base : Wheeled_APC {
		class TransportItems {
		};
	};
	
	class StrykerBase_EP1 : Wheeled_APC {
		class TransportItems {
		};
	};
	
	class Tank : LandVehicle {
		class TransportItems {
		};
	};
	
	class M113_Base : Tank {};
	
	class Tracked_APC : Tank {};
	
	class BMP2_Base : Tracked_APC {};
	
	class BRDM2_HQ_Base : BRDM2_Base {
		class TransportItems {
		};
	};
	
	class BTR90_HQ : BTR90_Base {
		class TransportItems {
		};
	};
	
	class LAV25_HQ : LAV25_Base {
		class TransportItems {
		};
	};
	
	class BMP2_HQ_Base : BMP2_Base {
		class TransportItems {
		};
	};
	
	class HMMWV_Ambulance : HMMWV_Base {
		class TransportItems {
		};
	};
	
	class GAZ_Vodnik_MedEvac : GAZ_Vodnik {
		class TransportItems {
		};
	};
	
	class S1203_ambulance_EP1 : S1203_TK_CIV_EP1 {
		class TransportItems {
		};
	};
	
	class LandRover_Ambulance_ACR : LandRover_ACR {
		class TransportItems {
		};
	};
	
	class M113Ambul_Base : M113_Base {
		class TransportItems {
		};
	};
	
	class BMP2_Ambul_Base : BMP2_Base {
		class TransportItems {
		};
	};
	
	class M1133_MEV_EP1 : StrykerBase_EP1 {
		class TransportItems {
		};
	};
	
	class Smallboat_1 : Ship {
		class TransportItems {
		};
	};
	
	class SmallShip : Ship {
		class TransportItems {
		};
	};
	
	class Fishing_Boat : Ship {
		class TransportItems {
		};
	};
	
	class Boat : Ship {};
	
	class PBX_ACR : Ship {
		class TransportItems {
		};
	};
	
	class RHIB : Boat {
		class TransportItems {
		};
	};
	
	class RubberBoat : Boat {
		class TransportItems {
		};
	};
	
	class GunShip : Helicopter {
		class TransportItems {};
	};
	
	class TransportHelicopter : Helicopter {
		class TransportItems {};
	};
	
	class AH1_Base : Helicopter {
		class TransportItems {};
	};
	
	class Kamov_Base : Helicopter {
		class TransportItems {};
	};
	
	class CruiseMissile1 : Helicopter {
		class TransportItems {};
	};
	
	class AH64_base_EP1 : Helicopter {
		class TransportItems {};
	};
	
	class AW159_Lynx_BAF : Helicopter {
		class TransportItems {};
	};
	
	class Ka137_Base_PMC : Helicopter {
		class TransportItems {};
	};
	
	class UH1_Base : Helicopter {
		class TransportItems {
		};
	};
	
	class UH60_Base : Helicopter {
		class TransportItems {
		};
	};
	
	class Mi17_base : Helicopter {
		class TransportItems {
		};
	};
	
	class Mi24_Base : Helicopter {
		class TransportItems {
		};
	};
	
	class AH6_Base_EP1 : Helicopter {
		class TransportItems {
		};
	};
	
	class UH1H_base : Helicopter {
		class TransportItems {
		};
	};
	
	class CH47_base_EP1 : Helicopter {
		class TransportItems {
		};
	};
	
	class UH60M_base_EP1 : UH60_Base {};
	
	class UH60M_US_base_EP1 : UH60M_base_EP1 {};
	
	class BAF_Merlin_HC3_D : Helicopter {
		class TransportItems {
		};
	};
	
	class Ka60_Base_PMC : Helicopter {
		class TransportItems {
		};
	};
	
	class Mi17_medevac_base : Mi17_base {
		class TransportItems {
		};
	};
	
	class MH60S : UH60_Base {
		class TransportItems {
		};
	};
	
	class UH60M_MEV_EP1 : UH60M_US_base_EP1 {
		class TransportItems {
		};
	};
	
	class Fighter : Plane {
		class TransportItems {};
	};
	
	class CargoAirplane : Plane {
		class TransportItems {};
	};
	
	class BIS_Steerable_Parachute : Plane {
		class TransportItems {};
	};
	
	class Steerable_Parachute_EP1 : Plane {
		class TransportItems {};
	};
	
	class A10 : Plane {
		class TransportItems {};
	};
	
	class AV8B2 : Plane {
		class TransportItems {};
	};
	
	class F35_base : Plane {
		class TransportItems {};
	};
	
	class Su25_base : Plane {
		class TransportItems {};
	};
	
	class Su34 : Plane {
		class TransportItems {};
	};
	
	class L39_base : Plane {
		class TransportItems {};
	};
	
	class L159_base : Plane {
		class TransportItems {};
	};
	
	class MV22 : Plane {
		class TransportItems {
		};
	};
	
	class C130J : Plane {
		class TransportItems {
		};
	};
	
	class Camp_base : Strategic {};
	
	class MASH : Camp_base {
		class TransportItems {
		};
	};
	
	class BASE_WarfareBFieldhHospital : Camp_base {
		class TransportItems {
		};
	};
};
