// config.bin - 13:15:29 09/29/13, generated in 0.03 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#include "CfgPatches.hpp"
#include "CfgVehicles.hpp"
