// Generated by unRap v1.06 by Kegetys

class cfgAmmo {
	class BulletBase;	// External class reference
	
	class B_7x92_Ball : BulletBase {
		hit = 15;
		indirectHit = 0;
		indirectHitRange = 0;
		visibleFire = 22;	// how much is visible when this weapon is fired
		audibleFire = 18;
        caliber = 1.5;
		visibleFireTime = 3;	// how long is it visible
		cost = 1.2;
		airLock = true;
	};
};
