// Generated by unRap v1.06 by Kegetys

class CfgMagazines {
	class CA_Magazine;	// External class reference
	
	class kar98_mag : CA_Magazine {
		scope = public;
		displayName = "5Rnd. Kar98k";
		initSpeed = 700;
		ammo = "B_7x92_Ball";
        mass = 4;
		count = 5;
		picture = "\gms_k98\data\equip\m_k98_ca.paa";
		descriptionShort = "Caliber: 7.92x57mm Mauser <br/>Rounds: 5 <br/>Used in: Kar98k";
	};
};
