// config.bin - 16:30:01 08/04/13, generated in 0.02 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define true	1
#define false	0

#define private		0
#define protected		1
#define public		2

#include "CfgPatches.hpp"
#include "cfgAmmo.hpp"
#include "CfgMagazines.hpp"
#include "Mode_SemiAuto.hpp"
#include "Mode_FullAuto.hpp"
#include "cfgWeapons.hpp"
