// Generated by unRap v1.06 by Kegetys

class CfgMagazines {
	class HandGrenade;	// External class reference
	
	class HandGrenade_West : HandGrenade {};
	
	class BAF_L109A1_HE : HandGrenade_West {};
	
	class HandGrenade_East : HandGrenade_West {};
};
