// config.bin - 22:58:13 08/13/13, generated in 0.03 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#include "CfgPatches.hpp"
#include "CfgMagazines.hpp"
#include "CfgWeapons.hpp"
